name: pysolver_env
#channels:
#  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - numpy=1.23
    - scipy
    - matplotlib
    - pandas
    - ipython
    - black
    - cycler
    - sphinx
    - sphinx-book-theme
    - sphinx-rtd-theme
    - pydata-sphinx-theme
    - numpydoc
    - winshell
    - pywin32

